Update run-test-project.yaml
testing User trace

diff --git a/ace/environments/ci/tasks/run-test-project.yaml b/ace/environments/ci/tasks/run-test-project.yaml
--- a/ace/environments/ci/tasks/run-test-project.yaml
+++ b/ace/environments/ci/tasks/run-test-project.yaml
@@ -40,5 +40,25 @@ spec:
         sed -i "s/#userTrace: 'none'/userTrace: 'debug'/g" /tmp/test-workdir/server.conf.yaml
         
         IntegrationServer -w /tmp/test-workdir --test-project $(params.is-test-project)
+        
+        # Run sonar-scanner with code-coverage plug-in 
+        if [ "$?" != "0" ]; then
+           echo "test failed; exiting"
+           exit 1
+        else
+          echo "user trace generated by test"
+          ls -l /tmp/test-workdir/config/common/log/
+          #download sonar scan cli, if not using custom image run
+          curl --output /tmp/scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
+          #cd /tmp
+          #unzip scanner.zip
+          # more shell command for adding parametars for BCT plug-in
+          
+          #sonar-scanner \
+          #  -Dsonar.login=${SONARQUBE_USER} \
+          #  -Dsonar.password=${SONARQUBE_PASSWORD} \
+          #  -Dsonar.host.url=${SONARQUBE_URL} \
+          #  -Dsonar.projectKey=${APP_NAME}
+        fi    
   workspaces:
     - name: workspace
